rplugin/python3/deoplete/sources/typescript.py
When TS encounters a compilation error TSServer doesn't return the `request_seq` key. This fix prevent deoplete-typescript from crashing in these cases.
=> Fix missing 'request_seq' key error

rplugin/python3/ts.py
Hi, thanks for nice plugin!
When I used this plugin,  followin error occured.
```
error caught in async handler '/Users/pocari/.cache/dein/repos/github.com/mhartington/deoplete-typescript/rplugin/python3/ts.py:command:TSType []'
Traceback (most recent call last):
File "/Users/pocari/.cache/dein/repos/github.com/mhartington/deoplete-typescript/rplugin/python3/ts.py", line 124, in tstype
if not info['success']:
TypeError: 'NoneType' object is not subscriptable
```
So, I taken a request log, response was following.
```
{'seq': 0, 'type': 'event', 'body': {'diagnostics': [], 'configFile': '/Users/pocari/dev/tmp/20161107/ionic-conference-app/tsconfig.json'}, 'event': 'configFileDiag'}
```
I checked `send_request` method (in `client.py`)
```
if "request_seq" not in ret or ret["request_seq"] > …
```
=> fix error if "getDoc" method returns None

plugin/nvim-typescript.vim, rplugin/python3/deoplete/sources/typescript.py, rplugin/python3/nvim-typescript/__init__.py, rplugin/python3/nvim-typescript/dir.py
This is derived from the work that @DonnieWest has done in #39 but goes in a different direction.
Basically, I moved some of the auto-logic here to vim side (for some better control of things)
But, if a person has js support enabled, instead of sending default arguments to TSServer, just write out a jsconfig.json instead. A bit more long-lasting imo. 
I have js-support turned off for now, until I make a doc file.
@DonnieWest opinions?
=> feat(): jsSupport 

doc/nvim-typescript.txt, plugin/nvim_typescript.vim, rplugin/python3/nvim-typescript/__init__.py
Added `g:nvim_typescript#loc_list_item_truncate_after` to allow the user
to customize the length of location list items after a call to
`:TSRefs`, while not taking into account leading spaces.
Updated docs.
=> User customizable location list item length

after/plugin/nvim_typescript.vim
WebDevIcon integration caused the icon to be included in the path of the
file.
Got carried away, missed that 💩
=> bug(fzf): Files now opened w/ correct path

doc/nvim-typescript.txt
Noticed some minor spelling errors in the documentation when I was setting your plugin up. Great plugin by the way 😃
=> Fix some spelling errors in docs

README.md
Thanks for the plugin! 
This does a little bit of tidying to the README. More than happy to isolate the individual important changes (typos, extra spaces, etc.) if this is too all over the place; a lot of the red/green is coming from my editor reformatting everything to be sub 80 chars.
=> General cleanup for README

rplugin/python3/nvim-typescript/client.py
I was getting the following error:
```
error caught in async handler '/Users/artbit/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim-typescript:function:TSOnBufEnter [[]]'
Traceback (most recent call last):
File "/Users/artbit/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim-typescript/__init__.py", line 609, in on_bufenter
self.tsstart()
File "/Users/artbit/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim-typescript/__init__.py", line 72, in tsstart
self._client.setTsConfig()
File "/Users/artbit/.config/nvim/plugged/nvim-typescript/rplugin/python3/nvim-typescript/client.py", line 54, in setTsConfig
self.tsConfg = {"major": int(major), "minor": int(
ValueError: invalid literal for int() with base 10: 'message TS6029: 1'
```
Which was caused by `tsc` version …
=> More robust tsc version detection

rplugin/python3/deoplete/sources/typescript.py
Directory is `nvim_typescript` but `nvim-typescript` was being added to the import path. Fixes:
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/samfonseca/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 365, in load_sources
[deoplete]     Source = import_plugin(path, 'source', 'Source')
[deoplete]   File "/Users/samfonseca/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 91, in import_plugin
[deoplete]     module = SourceFileLoader(module_name, path).load_module()
[deoplete]   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
[deoplete]   File "<frozen importlib._bootstrap_external>", line 823, in load_module
[deoplete]   File "<frozen importlib._bootstrap_external>", line 682, in …
```
=> Fix "ModuleNotFoundError: No module named 'utils'"

rplugin/python3/nvim_typescript/client.py
I found nvim-typescript doesn't support nightly, of which the version string is `Version 2.7.0-dev.20180116`
We can simply ignore string after `-`
=> support nightly typescript

rplugin/python3/nvim_typescript/__init__.py
text with newlines cant be added to the buffer through the python -> vim
interface.
=> fix(TSImport): trim newlines from end of import statement

install.sh
Without specifying a shell upfront, the install script is being executed with the default shell of the user. Some shells don't support command concatenation via `&&` (e.g. [fish](https://fishshell.com/)) and will fail while executing the script. This PRs ensures, that it is always executed with `sh`, which should be available on every Unix/Linux based system.
=> fix(install): Specify shell for install script

rplugin/node/nvim_typescript/lib/index.js, rplugin/node/nvim_typescript/src/index.ts
This was unneeded and slowed things down a bit (for nothing).
=> misc(): Do not re-open current file.

README.md
In addition to the missing closing parenthesis, I was thinking that `dein` was clever enough to not need the `.sh` extension for the install script and spent quite some time pulling my hairs, not understanding why the plugin wouldn't work. Turns out you *do* need the `.sh` extension :P
=> Fix documentation for dein

rplugin/node/nvim_typescript/lib/diagnostic.js, rplugin/node/nvim_typescript/src/diagnostic.ts
Since diagnostics come from the current buffer, it makes sense to put them into the location list for that buffer.
This works better with plugins that use the quickfix list for global navigation, like https://github.com/BurntSushi/ripgrep
currently, you can't jump through a list of matching locations since it gets overwritten as soon as TSGetDiagnostics run
=> diagnostics placed into location list

autoload/ncm2/nvim_typescript.vim, ncm2-plugin/nvim_typescript.vim, rplugin/node/nvim_typescript/src/index.ts
as per ncm2/ncm2#33
minimal test vimrc:
```vim
execute 'source ' . $WORKSPACE_DIR . '/plug.vim'
call plug#begin($WORKSPACE_DIR)
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'ncm2/nvim-typescript', {'do': './install.sh'}
call plug#end()
autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
```
Demo:
It should be possible to add snippet support, based on [ncm2-ultisnips](http://github.com/ncm2/ncm2-ultisnips). Don't have the time to finish that part. My typescript skill is still on `Hello world` level.
@isczg Please test this PR.
=> Add ncm2 source

plugin/nvim_typescript.vim
The variable's name now matches the one from the documentation.
=> Remove underscore from queried server_path variable name

doc/nvim-typescript.txt
Vim complains of duplication helptags.  This patch uses references instead of tags to avoid this.
> Vim(helptags):E154: Duplicate tag "g:nvim_typescript#diagnostics_enable" in file /path/to/doc/nvim-typescript.txt
=> Use || instead of ** to avoid duplication of tags

install.sh
This fixes issues when executing the install.sh script while not
standing in the same directory as it.
=> install.sh: set the file location directory as working dir

install.sh
If you have only YARN installed, it will fail to install and cause
`E117: Unknown function: TSCloseWindow` to happens.
probably related to https://github.com/mhartington/nvim-typescript/issues/230
=> fail to install if no NPM installed

doc/nvim-typescript.txt, plugin/nvim_typescript.vim, rplugin/node/nvim_typescript/src/index.ts
Adds a variable that makes nvim-typescript not show the "Starting Server..." and "Server started" messages.
Fixes: https://github.com/mhartington/nvim-typescript/issues/234
=> add g:nvim_typescript#quiet_startup

README.md, autoload/health/nvim_typescript.vim
Documents required version of neovim to be at least v0.4.0.
Simplifies debugging missing functionality using `:checkhealth`
Closes #245
=> update required nvim version to 0.4.0

README.md
Adds Plug.vim and Dein.vim links in to the **Installation** section of the README.md
=> Add Plug.vim to examples description

rplugin/node/nvim_typescript/src/index.ts
After poking around in `getDef`, it seemed like this was the root cause of #269 — not the compiler API change I'd mistakenly initially pointed to.
Deleting the `console.warn` and recompiling with `install.sh` seemed to fix `:TSDef` for me. Not sure why, but... `¯\_(ツ)_/¯`
=> Delete stray console.warn that was blowing up TSDef (fixes #269)

rplugin/node/nvim_typescript/src/index.ts
Since the default value for `autoOpen` in `createQuickFixList(…, autoOpen = false)` has been changed to  `false`, `TSRefs` is doing nothing.
Calling `TSRefs` shows quick fix list containing all references.
macOS 10.15.3 terminal, tmux 2.9a, NVIM v0.4.3
```ts
call dein#begin(expand('~/.vim/dein'))
call dein#add('Shougo/dein.vim')
call dein#add('mhartington/nvim-typescript', {'build': './install.sh'}) 
call dein#end()
let g:nvim_typescript#quiet_startup = 1
```
1. start neovim with typescript file
2. position cursor under function (e.g.) you want the references
3. call `:TSRefs`
If I've misconfigured something, please let me know.
=> TSRefs does not auto open quick fix list
